stages:
  - install
  - build
  - deploy

variables:
  APP_NAME: mot-ai
  DEPLOY_USER: root
  DEPLOY_SERVER: 34.128.73.186
  DEPLOY_PATH: /home/rizqi_rifai/mot-ai
  NODE_ENV: production

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:current
  script:
    - npm ci

build_app:
  stage: build
  image: node:current
  script:
    - npm run build
  artifacts:
    paths:
      - .next
      - package.json
      - public

deploy_to_server:
  stage: deploy
  image: node:current
  before_script:
    - 'which ssh-agent || ( yum install -y openssh-clients )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "
        mkdir -p $DEPLOY_PATH &&
        cd $DEPLOY_PATH &&
        rm -rf .next node_modules
      "
    - scp -r .next package.json public $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "
        cd $DEPLOY_PATH &&
        npm install --omit=dev &&
        pm2 delete $APP_NAME || true &&
        pm2 start 'npm start' --name '$APP_NAME' &&
        pm2 save
      "
  only:
    - main