image: docker:24

services:
  - docker:24-dind

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_NAME: mot-ai-dev
  DEPLOY_USER: rizqi_rifai
  DEPLOY_SERVER: 34.128.73.186
  DEPLOY_PATH: /home/rizqi_rifai/mot-ai

before_script:
  - apk add --no-cache openssh-client nodejs npm

stages:
  - build
  - deploy

build_dev_image:
  stage: build
  script:
    - docker build -t $CONTAINER_NAME .
  tags:
    - runner-mot-ai

deploy_to_dev_server:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && git pull && docker-compose up -d --build"
  only:
    - main
  tags:
    - runner-mot-ai