stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_NAME: mot-ai-dev
  DEPLOY_USER: rizqi_rifai
  DEPLOY_SERVER: 34.128.73.186
  DEPLOY_PATH: /home/rizqi_rifai/mot-ai

build_dev_image:
  stage: build
  script:
    - docker build -t $CONTAINER_NAME .
  tags:
    - docker

run_dev_container:
  stage: deploy
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d -p 3000:3000 --name $CONTAINER_NAME -v $CI_PROJECT_DIR:/app $CONTAINER_NAME
  tags:
    - docker
  except:
    - main

deploy_to_dev_server:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( yum install -y openssh-clients )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && git pull && docker-compose up -d --build"
  only:
    - main
  tags:
    - docker