version: "3.9"

services:
  nextjs:
    container_name: mot-ai
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules