version: "3.9"

services:
  nextjs:
    container_name: mot-ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    # Jangan mount volume dari host ke container agar build .next tidak hilang